name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm install

      - name: Generate schema and types
        run: npm run generate

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test:ci

      - name: Lint
        run: npm run lint
